version: '3'
services:
  simiscore-syntax:
    build:   # build using Dockfile in this directory
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        gunicorn app.main:app 
          --bind 0.0.0.0:80 
          --timeout 180
          --worker-class uvicorn.workers.UvicornH11Worker 
          --workers ${NUM_WORKERS} 
          --worker-tmp-dir /dev/shm "
    ports:
      - "${API_PORT}:80"

# python -c 'import trankit; trankit.Pipeline(lang=\"german\", gpu=False, cache_dir=\"./cache\")' && 
